### ISSUE TITLE
Vim visual block mode highlight not appearing

### ISSUE THREAD

**Issue by Arax20** [kepano/obsidian-minimal#341] opened 2022-06-13 22:56 UTC
When selecting text in visual block mode in vim, the selection highlighting is only visible on the active line:
![image](https://user-images.githubusercontent.com/45805601/173460414-7809028d-7979-4b1c-852a-6a528125c69e.png)

Intended behaviour:
![image](https://user-images.githubusercontent.com/45805601/173460480-a4e1820b-70d8-4785-9716-7f1cc4c66338.png)

This is only a visual bug as block edits are still possible, just without visible selection and without a visible cursor for multicursor editing.

**Comment by kepano** [comment] 2022-06-13 23:59
This seems like a duplicate of #303

**Closed** 2022-10-23 18:47 UTC
