### ISSUE TITLE
Image Grid overwrites custom CSS image ALT selectors

### ISSUE THREAD

**Issue by Oblique82** [kepano/obsidian-minimal#562] opened 2023-04-25 07:44 UTC
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

6.3.2

### Describe the bug

Apologies I am not a coder - just trying to make my simple setup work
Thanksyou for your excellent theme and support for the community

"Image Grid" settings doesn't respect custom CSS image ALT selectors 
eg img[alt*="banner"] gets affected by image grid settings when it shouldn't

in other words I can't have a banner image with CSS at the top of my note, and enable image grids at the same time to display photos for my daily journal

### Debug info

SYSTEM INFO:
	Obsidian version: v1.2.5
	Installer version: v1.1.9
	Operating system: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 22.4.0
	Login status: logged in
	Catalyst license: vip
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v6.3.2
	Snippets enabled: 4
	Restricted mode: off
	Plugins installed: 19
	Plugins enabled: 19
		1: Advanced URI v1.35.0
		2: Bible Linker v1.4.4
		3: Calendar v1.5.10
		4: Contextual Typography v2.2.4
		5: Hider v1.2.4
		6: Hover Editor v0.11.9
		7: Icon Folder v1.7.0
		8: Kanban v1.5.2
		9: Minimal Theme Settings v6.3.1
		10: Natural Language Dates v0.6.1
		11: Periodic Notes v0.0.17
		12: Style Settings v1.0.3
		13: Task Collector (TC) v1.0.7
		14: Various Complements v8.1.0-beta3
		15: Find orphaned files and broken links v1.9.0
		16: Homepage v3.0.2
		17: Plugin Update Tracker v1.4.6
		18: Readwise Official v2.0.1
		19: Local images v0.14.2

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment] 2023-06-30 03:39
I was not able to reproduce this issue. It should be fixed in 7.0 but let me know if it isn't.

**Closed by kepano** 2023-06-30 03:39 UTC
Labels: bug
