### ISSUE TITLE
Low contrast text for exported PDFs

### ISSUE THREAD

**Issue by fabiosirna** [kepano/obsidian-minimal#243] opened 2022-03-20 22:12 UTC
**Describe the bug**
Exporting a PDF file generates low-contrast text, especially the headers.

**To reproduce**
1. Write some text
2. Export to PDF
3. Print a page

**Expected behavior**
More contrast in the text

**Screenshots**
![image](https://user-images.githubusercontent.com/2249234/159188170-bc5a707c-65b6-4b55-88fe-a80142ee87f6.png)

**Comment by kepano** [comment] 2022-03-20 22:19
Seems like a duplicate of #98

**Comment by fabiosirna** [comment] 2022-03-20 22:28
> Seems like a duplicate of #98

Yes, it is similar. I tried searching, but this issue didn't come up on the results page and I created a new one.

**Closed** 2022-03-21 00:19 UTC
Labels: bug, help wanted
