### ISSUE TITLE
Too small width between number and checkbox when ordered list+task

### ISSUE THREAD

**Issue by xshuai1006** [kepano/obsidian-minimal#457] opened 2022-10-19 12:13 UTC
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.0.13

### Describe the bug

default theme (without any other plugins): 
![image](https://user-images.githubusercontent.com/1651111/196686390-055b1787-01fc-46c1-83b7-e13a352103ba.png)
minimal theme (without any other plugins):
![image](https://user-images.githubusercontent.com/1651111/196686619-73d42b3c-4c21-44e5-98ce-44132830867f.png)

### Debug info

SYSTEM INFO:
	Obsidian version: v1.0.0
	Installer version: v1.0.0
	Operating system: Windows 10 Home China 10.0.22621
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 0
	Plugins enabled: 0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.

**Comment by kepano** [comment] 2022-10-19 14:20
Duplicate of #377

**Closed** 2022-10-19 14:21 UTC
Labels: bug, duplicate
