### ISSUE TITLE
UI request for customizable side panel in iPad mobile 

### ISSUE THREAD

**Issue by davebhc71** [kepano/obsidian-minimal#115] opened 2022-01-12 02:59 UTC
Because screen real estate is at a premium in Obsidian Mobile, could there be a setting(s) to shrink the size of the two (left & right) side panes.
![IMG_0502](https://user-images.githubusercontent.com/80698092/149056070-6ae21dca-2975-4de0-9e86-0d442115e1f8.jpeg)

**Comment by kepano** [comment] 2022-01-12 03:16
This is a duplicate of #101 — will investigate

**Closed by kepano** 2022-01-12 03:16 UTC
Labels: enhancement
