### ISSUE TITLE
Dataview inline fields with tags rendered incorrectly

### ISSUE THREAD

**Issue by rduwjjnh** [kepano/obsidian-minimal#462] opened 2022-10-20 20:13 UTC
### Is the bug present when using the default Obsidian theme?

Yes

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

6.0.13

### Describe the bug

When the Dataview plug-in is enabled there's an extra blob before the actual tag, both when using square brackets and parenthesis.
Edit mode - preview mode.
Minimal
![2022-10-20 22_53_46](https://user-images.githubusercontent.com/79216500/197046030-58da380c-7143-4e2f-8c9c-cdc6b387f8f7.png)
Default
![2022-10-20 22_57_19](https://user-images.githubusercontent.com/79216500/197046032-d5d43ea6-81fc-4ef4-942f-e409eadd2361.png)

### Debug info

SYSTEM INFO:
	Obsidian version: v1.0.0
	Installer version: v0.15.8
	Operating system: Windows 10 Enterprise 10.0.19044
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: on

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.

**Comment by kepano** [comment] 2022-10-23 21:23
Duplicate of #159

**Closed by kepano** 2022-10-23 21:23 UTC
Labels: bug
