### ISSUE TITLE
BUG:Misplaced YAML split line in document

### ISSUE THREAD

**Issue by MugenLee** [kepano/obsidian-minimal#305] opened 2022-05-11 08:29 UTC
In mini: v5.2.5, obsidian: v0.14.10

In normal documents, and documents opened by hover edit
The "---" dividing line at the beginning of YAML is dislocated and moved to the far left

After testing, as long as "---" is changed to a new line, the normal display can be restored

But the history file will have a lot of YAML "---" is written at the beginning

As shown below:

![image](https://user-images.githubusercontent.com/91043731/167803882-246abe58-9a0a-416d-8d9f-9a826645426f.png)

![image](https://user-images.githubusercontent.com/91043731/167804619-b14907f9-4aa8-41b5-b935-893c4751d17c.png)

**Comment by kepano** [comment] 2022-05-11 15:02
This is a duplicate of #301

This issue is now fixed if you update to the latest

**Closed by kepano** 2022-05-11 15:02 UTC
Labels: bug
