### ISSUE TITLE
Live preview and reading mode the same for img-grid

### ISSUE THREAD

**Issue by spiritualgeek** [kepano/obsidian-minimal#316] opened 2022-05-21 07:31 UTC
**Is your feature request related to a problem? Please describe.**
Is it not possible to have `img-grid` work in live preview mode?

**Describe the solution you'd like**
I would like `img-grid` to behave the same in live preview as it does in reading mode

**Comment by kepano** [comment] 2022-05-21 13:53
This is a duplicate of #76 and #225

Unfortunately this is currently impossible without changes to Obsidian

**Closed by kepano** 2022-05-21 13:53 UTC
Labels: duplicate, enhancement, external-dependency

**Comment by spiritualgeek** [comment] 2022-05-21 16:11
Then why not implement as a callout? - See ITS from line 211 - https://github.com/SlRvb/Obsidian--ITS-Theme/blob/a56438e6847f26dd4d8e337a21a225a20b0a994d/S%20-%20Callouts.css

What is the current limitation?

Apologies for duplication

**Comment by kepano** [comment] 2022-05-21 16:19
The problem is there is no container in LP for groups of images, see explanation in the other issues

The callout is just a completely different approach that wouldn't be compatible with the existing img-grid code

**Comment by spiritualgeek** [comment] 2022-05-21 16:42
Thanks - I will scan through the others. Any chance of implementing as a callout? - I think there would be a fair number of users using snippets and avoiding the 'img-grid' (incl me)

**Comment by kepano** [comment] 2022-05-21 18:02
I think this is a discussion for Obsidian Discord. I believe there already multiple community snippets that do this
