### ISSUE TITLE
Panel buttons not visible in Excalidraw window.

### ISSUE THREAD

**Issue by kuros** [kepano/obsidian-minimal#491] opened 2022-11-14 04:26 UTC
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

6.1.0

### Describe the bug

I have installed Excalidraw plugin in Obsidian, After using minimal theme in dark mode (dracula), All the panel objects are not visible. Already raised it with obsidian-excalidraw (https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/877). they suggest it to be minimal theme issue.

Steps to reproduce:
install minimal theme
Install Minimal Theme Settings plugin
Choose the dark mode schema as Dracula
Setting --> Appearance --> Base color scheme = "Dark"

<img width="1147" alt="Screenshot 2022-11-09 at 9 52 43 AM" src="https://user-images.githubusercontent.com/11554554/201575068-c3225013-3194-49de-98a6-ff36d23569ce.png">

### Debug info

SYSTEM INFO:
Obsidian version: v1.0.3
Installer version: v0.13.23
Operating system: Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64 21.6.0
Login status: not logged in
Insider build toggle: off
Live preview: on
Legacy editor: off
Base theme: dark
Community theme: Minimal
Snippets enabled: 0
Restricted mode: off
Plugins installed: 2
Plugins enabled: 2
1: Excalidraw v1.7.27
2: Minimal Theme Settings v6.1.0

**Comment by kuros** [comment] 2022-11-28 06:12
Reported the issue to Excalidraw Plugin, they reported it to be theme issue:

https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/877

**Comment by kepano** [comment] 2022-11-28 17:04
Duplicate of #427

**Closed by kepano** 2022-11-28 17:04 UTC
Labels: bug
