### ISSUE TITLE
Checkbox not rendered correctly when used with the numbered list

### ISSUE THREAD

**Issue by icebruce** [kepano/obsidian-minimal#417] opened 2022-09-12 23:13 UTC
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.0.4

### Describe the bug

Small alignment issue with check boxes when used with a numbered list.
Does not seem affect the default theme, only minimal.

Default theme
![image](https://user-images.githubusercontent.com/66655064/189774158-ca0b8698-82d6-4f61-a856-71f4bf73b80d.png)

Minimal
![image](https://user-images.githubusercontent.com/66655064/189774176-dec1b6ff-e973-46a0-a344-b27fcf7b760b.png)

### Debug info

SYSTEM INFO:
	Obsidian version: v0.16.2
	Installer version: v0.14.6
	Operating system: Windows 10 Enterprise 10.0.19044
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 4
	Restricted mode: off

**Comment by kepano** [comment] 2022-10-16 20:08
Seems like a duplicate of #377

**Closed by kepano** 2022-10-16 20:08 UTC
Labels: bug
