### ISSUE TITLE
Tables in Live Preview De-Dented

### ISSUE THREAD

**Issue by newmanb** [kepano/obsidian-minimal#298] opened 2022-05-09 22:15 UTC
**Before you open a bug report**
Disable plugins and snippets that could be causing a conflict. Update to the latest versions of the following, and restart Obsidian:

- Minimal Theme
- Minimal Theme Settings plugin
- Contextual Typography plugin

**Confirm that the bug is not present when Minimal theme is off**
Not present in default theme

**Describe the bug**
Tables in live preview appear de-dented when rendered as a table, but indent properly when being edited.

**To reproduce**
1. Open a note
2. Add a table using markdown
3. Table indents properly while adding and editing
4. Table dedents when rendered as a table in live preview

**Expected behavior**
I expect the table to indent in line with the left-most text margin on the page

**Screenshots**
<img width="686" alt="Minimal Dedented Table" src="https://user-images.githubusercontent.com/28424218/167507297-97837a6d-e251-4e7f-9545-8c27b833e5b1.png">
<img width="668" alt="Default Indented Table" src="https://user-images.githubusercontent.com/28424218/167507308-76cba749-f95c-404f-b519-2ecc050a6213.png">

**Debug info (required):**
SYSTEM INFO:
	Obsidian version: v0.14.9
	Installer version: v0.14.6
	Operating system: Windows 10 Home 10.0.22000
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 0
	Safe mode: off
	Plugins installed: 25
	Plugins enabled: 23
		1: Calendar
		2: QuickAdd
		3: Tasks
		4: Dataview
		5: Kanban
		6: Obsidian42 - BRAT
		7: Collapse All
		8: Templater
		9: Tag Wrangler
		10: MetaEdit
		11: Get Info
		12: Hider
		13: Various Complements
		14: Readwise Official
		15: Style Settings
		16: Obsidian42 - Text Transporter
		17: Better footnote
		18: Customizable Sidebar
		19: Periodic Notes
		20: Emoji Toolbar
		21: Omnisearch
		22: Minimal Theme Settings
		23: Advanced Tables

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

**Comment by kepano** [comment] 2022-05-09 22:26
What version of Minimal Theme are you using?

**Comment by newmanb** [comment] 2022-05-09 22:31
> What version of Minimal Theme are you using?

5.2.4 per the manage themes window.
<img width="718" alt="image" src="https://user-images.githubusercontent.com/28424218/167509220-a7a0957b-5ffc-4551-86d9-e342f9ac377d.png">

**Comment by kepano** [comment] 2022-05-09 22:40
Can you share the markdown source code for your note? I am not able to reproduce the issue on my end.

**Comment by newmanb** [comment] 2022-05-09 22:44
> Can you share the markdown source code for your note? I am not able to reproduce the issue on my end.

Test

| A      | B   | C   |
| ------ | --- | --- |
| Test   |     |     |
| Test 2 |     |     |
| Test 3 |     |     |
| Test 4 |     |     |



[Untitled.md](https://github.com/kepano/obsidian-minimal/files/8655823/Untitled.md)

**Comment by kepano** [comment] 2022-05-09 22:52
I am not able to reproduce this issue :/

I wonder if you have a plugin or snippet that is somehow interfering. Would you mind trying this in a new vault?

**Comment by newmanb** [comment] 2022-05-09 23:03
> I am not able to reproduce this issue :/
> 
> I wonder if you have a plugin or snippet that is somehow interfering. Would you mind trying this in a new vault?

Interesting. Works fine in a new vault. Disabled all plugins and snippets in the original vault and it still happens though.

<img width="244" alt="image" src="https://user-images.githubusercontent.com/28424218/167512381-2048810e-c06b-460c-952a-21d212ecadae.png">


SYSTEM INFO:
	Obsidian version: v0.14.9
	Installer version: v0.14.6
	Operating system: Windows 10 Home 10.0.22000
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 0
	Safe mode: off
	Plugins installed: 25
	Plugins enabled: 0

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.

**Comment by newmanb** [comment] 2022-05-09 23:04
Oh! Try turning off 'Readable Line Length'.

**Comment by kepano** [comment] 2022-05-10 00:52
This should now be fixed in 5.2.5

**Closed by kepano** 2022-05-10 00:52 UTC
Labels: bug
