### ISSUE TITLE
Block Reference Highlighting Boxing issue for Live Preview mode

### ISSUE THREAD

**Issue by alicangok** [kepano/obsidian-minimal#408] opened 2022-09-06 15:54 UTC
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

5.3.2

### Describe the bug

Upon clicking a block link, the newly opened page has "ugly" boxes all over different components.

(I disabled all other plugins and snippets. I even did a fresh vault and only switched the theme to Minimal, but the issue still persists on both dark and light modes.)

<img width="889" alt="image" src="https://user-images.githubusercontent.com/26303095/188681163-dc541172-0692-438d-a03f-7a57fe6f3eb2.png">

### Debug info

SYSTEM INFO:
	Obsidian version: v0.15.9
	Installer version: v0.14.6
	Operating system: Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101 21.2.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: on

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.

**Comment by kepano** [comment] 2022-09-06 17:05
This is a duplicate of #376, it's also an Obsidian issue not Minimal and has already been fixed if you upgrade to Obsidian 0.16

**Closed** 2022-09-06 17:05 UTC
Labels: bug
