### ISSUE TITLE
Text moving and hiding

### ISSUE THREAD

**Issue by gabrielcarus** [kepano/obsidian-minimal#606] opened 2023-07-05 14:40 UTC
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.0.5

### Describe the bug

When I type something on the limit of the line length, the text moves and part of the text on the left side gets covered (you can see that part of the number 1. on the top and the "W" in "War" disappears), and the text stays like this while I type. Sometimes moves enough for the whole number "1." to disappear completely. (I'll attach the video here)

The debug info is from a text I did on my sandbox.
Video: https://drive.google.com/file/d/1DFLDMZYeEf9dhlmszuRM0jLrnKFiTEh4/view?usp=sharing

### Debug info

The debug info is from my sandbox (that's why the absence of plugins and snippets)

SYSTEM INFO:
	Obsidian version: v1.3.5
	Installer version: v1.3.5
	Operating system: Darwin Kernel Version 22.5.0: Thu Jun  8 22:21:34 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8112 22.5.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v7.0.5
	Snippets enabled: 0
	Restricted mode: on

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.

**Comment by MichaelHHeng** [comment] 2023-07-07 09:13
Here the same. I think this display bug is related to the bug "Horizontal scrolling is not working #604" and the bug "Missing caret for folding headers #603". Here is a video of mine:

https://github.com/kepano/obsidian-minimal/assets/122787238/557aaf5b-1f82-4ae7-b6f0-3fd4cc18007c

**Comment by kepano** [comment] 2023-07-08 20:35
I am not able to reproduce this. Maybe it is fixed in 7.0.6

If not, I need more detail, is readable line length on or off in Settings → Editor?

**Comment by pyxelr** [comment] 2023-07-08 22:04
I also cannot replicate it now since 7.0.6, and I have used to keep “readable line length” as disabled.

**Comment by kepano** [comment] 2023-07-09 00:36
Closing for now, please reopen if you can provide repro steps

**Closed by kepano** 2023-07-09 00:36 UTC
Labels: bug

**Comment by MichaelHHeng** [comment] 2023-07-10 08:00
I think it's fixed, I can't replicate it in 7.0.7, “readable line length” enabled and disabled. Thanks!
